name: Community Store (HACS)
on: [push, release]

jobs:
  hacs:
    runs-on: "ubuntu-latest"
    steps:
        - uses: "actions/checkout@v3"
        - uses: "hacs/action@main"
          with:
            category: integration
            ignore: archived
            
